In [1]:
import numpy as np
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect('backend/db.sqlite3');

In [18]:
df = pd.read_sql_query("SELECT *, strftime('%Y-%m', review_date) YearMonth, strftime('%Y-%W', review_date) YearWeek FROM shopify_scraper_review WHERE app_id = 47", conn);

In [22]:
df.groupby(['YearMonth'])['rating'].mean()

YearMonth
2018-03    5.000000
2018-04    4.200000
2018-05    5.000000
2018-06    4.800000
2018-07    4.000000
2018-08    3.666667
2018-09    5.000000
2018-10    5.000000
2018-11    5.000000
2018-12    5.000000
2019-01    4.909091
2019-02    5.000000
2019-03    5.000000
2019-04    5.000000
2019-05    4.375000
2019-06    4.571429
2019-07    4.529412
2019-08    4.833333
2019-09    5.000000
2019-10    4.750000
2019-11    5.000000
2019-12    4.384615
2020-01    4.875000
2020-02    4.000000
2020-03    4.500000
2020-04    5.000000
2020-05    4.285714
2020-06    3.875000
2020-07    5.000000
2020-08    5.000000
2020-09    4.166667
2020-10    5.000000
2020-11    4.750000
2020-12    5.000000
2021-01    5.000000
2021-02    5.000000
2021-03    5.000000
2021-04    5.000000
2021-05    4.750000
2021-06    4.571429
2021-07    5.000000
2021-08    4.857143
2021-09    5.000000
2021-10    5.000000
2021-11    5.000000
2021-12    5.000000
2022-01    5.000000
2022-02    5.000000
2022-03    5.000000
2022-04    5.000000
2022-05    5.000000
2022-06    4.555556
2022-07    5.000000
2022-08    5.000000
2022-09    5.000000
2022-10    4.909091
2022-11    5.000000
2022-12    5.000000
2023-01    5.000000
2023-02    5.000000
Name: rating, dtype: float64

In [27]:
df[['YearMonth', 'rating']].groupby('YearMonth').agg(['count','mean'])

          rating
           count      mean
YearMonth
2018-03        3  5.000000
2018-04        5  4.200000
2018-05        6  5.000000
2018-06        5  4.800000
2018-07        8  4.000000
2018-08        3  3.666667
2018-09        7  5.000000
2018-10        7  5.000000
2018-11        5  5.000000
2018-12        5  5.000000
2019-01       11  4.909091
2019-02        4  5.000000
2019-03       12  5.000000
2019-04       11  5.000000
2019-05       16  4.375000
2019-06        7  4.571429
2019-07       17  4.529412
2019-08       12  4.833333
2019-09       11  5.000000
2019-10       16  4.750000
2019-11        5  5.000000
2019-12       13  4.384615
2020-01        8  4.875000
2020-02       12  4.000000
2020-03        4  4.500000
2020-04        7  5.000000
2020-05       14  4.285714
2020-06        8  3.875000
2020-07        2  5.000000
2020-08       10  5.000000
2020-09        6  4.166667
2020-10        5  5.000000
2020-11        4  4.750000
2020-12        4  5.000000
2021-01        4  5.000000
2021-02        3  5.000000
2021-03        2  5.000000
2021-04        3  5.000000
2021-05        8  4.750000
2021-06        7  4.571429
2021-07       13  5.000000
2021-08        7  4.857143
2021-09        5  5.000000
2021-10        5  5.000000
2021-11        3  5.000000
2021-12        4  5.000000
2022-01        2  5.000000
2022-02        4  5.000000
2022-03        2  5.000000
2022-04        7  5.000000
2022-05        6  5.000000
2022-06        9  4.555556
2022-07       11  5.000000
2022-08        6  5.000000
2022-09        8  5.000000
2022-10       11  4.909091
2022-11       11  5.000000
2022-12       17  5.000000
2023-01       14  5.000000
2023-02        6  5.000000

In [29]:
df = pd.read_sql_query("SELECT rating, review_date FROM shopify_scraper_review WHERE app_id = 47", conn);

In [30]:
test_month = df.groupby(pd.Grouper(key='review_date', freq='M'))

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'